name: discussion-to-todoist

on:
  discussion:
    types: [created]
  discussion_comment:
    types: [created]
  push:
  workflow_dispatch:

jobs:
  new-todoist:
    uses: justinjbird/workflow/.github/workflows/notify-todoist.yml@main
    with:
      title: "New activity in comments on [blog](https://github.com/justinjbird/site-blog-comments/discussions) ${{ inputs.discussion.title }}"
      description: "${{ inputs.discussion_comment.body }}"
      labels: "anywhere,scheduled,5"
      priority: 2
      due_string: "today"
      project_id: 2287192456 # blog
    secrets:
      token: ${{ secrets.TODOIST_API_TOKEN }}
