name: notify-on-discussion

on:
  discussion:
    types: [created, edited, answered]
  discussion_comment:
    types: [created, edited]
  push:

jobs:
  teams-message:
    uses: justinjbird/workflow/.github/workflows/message-teams.yml@main
    with:
      message: "New activity in comments on [blog](https://github.com/justinjbird/site-blog-comments/discussions)"
    secrets:
      webhook: "${{ secrets.TEAMS_WEBHOOK_CXO_JUSTIN }}"
  todoist-task:
    uses: justinjbird/workflow/.github/workflows/new-todoist.yml@main
    with:
      title: "New activity in comments on [blog](https://github.com/justinjbird/site-blog-comments/discussions)"
      labels: blog, scheduled
      priority: 3
      due_string: "today"
      project_id: 2192133472
    secrets:
      token: "${{ secrets.TODOIST_TOKEN }}"
  raise-error:
    uses: justinjbird/workflow/.github/workflows/message-teams.yml@main
    if: failure()
    with:
      message: "${{ github.action }} action failed"
    secrets:
      webhook: "${{ secrets.TEAMS_WEBHOOK_CXO_JUSTIN }}"
