name: notify-on-discussion

on:
  discussion:
    types: [created, edited, answered]
  discussion_comment:
    types: [created, edited]
  push:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Create task in Todoist
        run: |
          curl -X POST https://api.todoist.com/rest/v2/tasks --data '{\"content\": \"New Comment Added\", \"description\":\"https://github.com/justinjbird/site-blog-comments/discussions\", \"labels\": [\"web\",\"scheduled\"], \"priority\": 2, \"due_string\": \"today\", \"project_id\": \"2287192456\"}' -H "Content-Type: application/json" -H "Authorization: Bearer ${{ secrets.TODOIST_API_TOKEN }}"
        shell: pwsh
